### ISSUE TITLE
Definir e implementar arquitetura de eventos do sistema.

### ISSUE THREAD

**Issue by vladymir** [vladymir/MiHealth#2]
Fazer toda a comunicação interna usando o eventBus.

**Comment by nelsoncarnauba** [comment]
Documento iniciado em 
https://docs.google.com/document/d/1mATpqPqayLs8gpRkj6EpEoF7ive9g5eZzMllLNgMIpM/edit

**Comment by nelsoncarnauba** [comment]
Documento iniciado em
https://docs.google.com/document/d/1mATpqPqayLs8gpRkj6EpEoF7ive9g5eZzMllLNgMIpM/edit

**Comment by vladymir** [comment]
É preciso definir quais eventos iremos disparar e capturar. Exemplo: eventBus.post(new UploadData(data)); eventBus.post(new GetLocation());

**Comment by nelsoncarnauba** [comment]
Fiz a entrega para os professores da v 1 do doc, mas podemos/deveremos evoluir essa versão para definir o padrão para essa notificação dos eventos. Por enquanto, acho que podemos deixar com o escopo aberto para dar mais flexibilidade.
Vamos interagindo em relação a esse tópico. A issue ficará aberta por enquanto.

**Comment by nelsoncarnauba** [comment]
close #2
